---
swagger: "2.0"
info:
  version: "3.0"
  title: 0g-chain Light Client RPC
  description: A REST interface for state queries, transaction generation and broadcasting.
tags:
  - name: Vesting
    description: Validator vesting module APIs
schemes:
  - https
host: api.data.0g-chain.io
securityDefinitions:
  kms:
    type: basic
paths:
  /vesting/circulatingsupply:
    get:
      deprecated: true
      summary: Get the current circulating supply of 0g-chain
      tags:
        - Vesting
      produces:
        - application/json
      responses:
        200:
          description: 0g-chain circulating supply
          schema:
            properties:
              height:
                type: string
                example: "100"
              result:
                type: string
                example: "81443180"
        500:
          description: Server internal error
  /vesting/totalsupply:
    get:
      deprecated: true
      summary: Get the total supply of 0g-chain
      tags:
        - Vesting
      produces:
        - application/json
      responses:
        200:
          description: 0g-chain total supply
          schema:
            properties:
              height:
                type: string
                example: "100"
              result:
                type: string
                example: "120000000"
        500:
          description: Server internal error
  /vesting/circulatingsupplyhard:
    get:
      deprecated: true
      summary: Get the current circulating supply of HARD
      tags:
        - Vesting
      produces:
        - application/json
      responses:
        200:
          description: HARD circulating supply
          schema:
            properties:
              height:
                type: string
                example: "100"
              result:
                type: string
                example: "63750000"
        500:
          description: Server internal error
  /vesting/totalsupplyhard:
    get:
      deprecated: true
      summary: Get the total supply of HARD
      tags:
        - Vesting
      produces:
        - application/json
      responses:
        200:
          description: HARD total supply
          schema:
            properties:
              height:
                type: string
                example: "100"
              result:
                type: string
                example: "200000000"
        500:
          description: Server internal error
  /vesting/circulatingsupplyswp:
    get:
      deprecated: true
      summary: Get the current circulating supply of SWP
      tags:
        - Vesting
      produces:
        - application/json
      responses:
        200:
          description: SWP circulating supply
          schema:
            properties:
              height:
                type: string
                example: "100"
              result:
                type: string
                example: "63750000"
        500:
          description: Server internal error
  /vesting/circulatingsupplyusdx:
    get:
      deprecated: true
      summary: Get the current circulating supply of USDX
      tags:
        - Vesting
      produces:
        - application/json
      responses:
        200:
          description: USDX circulating supply
          schema:
            properties:
              height:
                type: string
                example: "100"
              result:
                type: string
                example: "63750000"
        500:
          description: Server internal error
  /vesting/totalsupplyusdx:
    get:
      deprecated: true
      summary: Get the total supply of USDX
      tags:
        - Vesting
      produces:
        - application/json
      responses:
        200:
          description: USDX total supply
          schema:
            properties:
              height:
                type: string
                example: "100"
              result:
                type: string
                example: "200000000"
        500:
          description: Server internal error
